name: Build and Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-pnpm:
    name: Build + Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/cache-asdf

    - name: Set up Cargo cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - name: Set up pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Setup
      run: |
        ./build.sh setup

    - name: Build
      run: |
        ./build.sh build

    - name: Test
      run: |
        ./build.sh test

    - run: asdf current
